_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.9.22
        t:
            "1":
                - 1
                - 41
                - 49
                - 55
                - 63
            "3":
                - 23
                - 55
            "4": 3.9.22
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
